CREATE TABLE WT0010
    ( 
        WT0_ID INT NOT NULL AUTO_INCREMENT
        , WT0_NAME VARCHAR(50)
        , WT0_TIME VARCHAR(50)
        , WT0_TEMP FLOAT(0.0)
        , WT0_HUM FLOAT(0.0)
        , PRIMARY KEY (WT0_ID)
    );